### ISSUE TITLE
Legal issue

### ISSUE THREAD

**Issue by notsodaredevil** [timiimit/UT4MasterServer#216]
Hi,

**Steps to reproduce:**
1. [European Parliament declares Russia to be a state sponsor of terrorism. ](https://www.eeas.europa.eu/delegations/ukraine/european-parliament-declares-russia-be-state-sponsor-terrorism_en)
2. A lot of European countries have laws regarding ban of approval of terrorism
3. Master server located in Europe region (eu-central-1) and should comply with European laws
4. There enough russian players that during the game publicly approve war and terrorism activity in game chat
5. It is possible to write complain to service provider (AWS) regarding violation of EU laws to shutdown server (35.158.152.164) and/or whole AWS account

**Desired behavior:**
1. Such players (e.g. pechora, alexss) are banned by IP on master server level 
2. Master server website have form for reporting such cases (with mandatory screenshot upload to exclude false reporting)

Alternative solutions:
1. [Block access to master server for russians by geoip](https://thenerdstash.com/ukrainian-officials-request-gaming-industry-to-block-russian-access/)

**Actual behavior:**
Some players continue spread lie and approve war, that lead to risks that server will be reported and closed forever

**Comment by timiimit** [comment]
This master server project is just a service allowing people to have a unified location from where to get a list of servers and track player's stats and similar information. The alleged offences that took place happened in the game while connected to a server hosted by individuals that are in no way affiliated with this project. Master server had no direct involvement allowing such speech take place, because all in-game chat traffic happens directly between server that is hosting the match and players playing in that match.

I personally have not seen a single person approve war or anything like that in the game. But If your allegations are true, then i'm sure that UT4 community would agree to ban (or just mute, since its only their words that are problematic) said players from the hubs. If you let me know exactly who (preferably account id) and on which hub these accidents took place, i can try to contact owners of that hub and have them verify chat history to see whether this really happened or not and take further action.

*btw, im not sure why you formatted this in a way as if this is a bug report.*

**Comment by notsodaredevil** [comment]
Hm, seems technically you are right, in game communications goes directly through hub server. Confused this with XMPP that (should) run atop master server... 
If I'm not wrong you are planning to add XMPP for MS, so then such issue will be actual also for MS. But seems it wouldn't happen any time soon, so ok



> If you let me know exactly who (preferably account id) and on which hub these accidents took place, i can try to contact owners of that hub and have them verify chat history to see whether this really happened or not and take further action.

I'm sure they were `21bc5a58badf8fcfa0101f25eee5871a` and `222f5dea1e33da662d989a0750055910` on hubs `"Unreal-Battles - DE"` or `"Unreal-Battles - UK"` I believe. There were also other names but I'm not remember who exactly. In most cases I have to just mute communication to not see all this dirt. After loosing home and lives of people you care - such bullshit just hurts.
But I'm not agree that just mute is enough. It is the same as to say robbery doesn't happen if you don't see it.

> btw, im not sure why you formatted this in a way as if this is a bug report.

Sorry about confusion, dunno why I did so. Just got used to this, probably some kind of prof. deformation

**Comment by timiimit** [comment]
XMPP will only handle friend chat communication.

I let Supsun know about your dispute. He will look at chat history when he finds the time. You can talk to him to get further information on what action will be taken.
